[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.8.1"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "^3.3.3"

[[constraint]]
  name = "github.com/asecurityteam/logevent"
  version = "^1.0.4"

[[constraint]]
  branch = "master"
  name = "github.com/rs/xstats"

[[constraint]]
  name = "github.com/golang/mock"
  version = "^1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "^1.3.0"

[[override]]
  name = "github.com/asecurityteam/runhttp"
  version = "^0.2.0"

[[override]]
  name = "github.com/asecurityteam/settings"
  version = "^0.1.0"
